### PR TITLE
Document when a CORS policy is required for serving images

### PR DESCRIPTION
**Pull request by phloxic**

### CODE REVIEW

**Comment by nnarhinen** [comment]
Is this true? The images are loaded as background-image. Does it really need CORS headers?

**Comment by phloxic** [comment]
Entirely possilbe I've become too paraonoid about this stuff. But worth testing in practice imho, but I've now run out of servers without CORS and http://cdn.rawgit.com/nnarhinen/flowplayer-thumbnails/master/example/thumbnails/bauhaus{time}.jpg have CORS headers ...

**Comment by nnarhinen** [comment]
http://codepen.io/anon/pen/pjKppB

```
Niklas-Narhinen-MacBook-Pro:~ nnarhinen$ curl -I https://flowplayer.org/media/img/logo.png
HTTP/1.1 200 OK
Date: Fri, 30 Oct 2015 19:53:26 GMT
Content-Type: image/png
Content-Length: 2193
Connection: keep-alive
x-amz-id-2: t1w+UO6g4PhoLPHDg3cd1KpLnATTpSvUMLb8APD/ZsrlY7O965xTJO3Z1bqbBWyhwkHsU5TqmZs=
x-amz-request-id: 19041F40E6529445
Last-Modified: Wed, 16 Jan 2013 07:11:43 GMT
ETag: "6660ade62c595065f625d164b64f67a3"
Server: NetDNA-cache/2.2
X-Cache: HIT
```

**Comment by phloxic** [comment]
Yeah, I also tested on a virtual local server and loaded from blacktrash.org, no prob.
Closing. But just because I'm paranoid doesn't mean they're not out to get me ;-)

**Pull request closed without merging**
