### PR TITLE
More than 1 second between every thumbnail

### PR DESCRIPTION
**Pull request by Dalesjo**
Hi

I have added the optional option "interval" to specify how many seconds you want between every thumbnail so you don't need to create one for every second. filename convention is the same as before.

example:
http://samuel.dalesjo.com/other/flowplayer-thumbnail-fork/
_use the slider below to adjust how many seconds you want between every thumbnail_

comments?

### CODE REVIEW

**Comment by nnarhinen** [comment]
I like this, thanks!

@blacktrash Can you take a look and merge if you think it's ok :)

**Comment by phloxic** [comment]
@Dalesjo - will look into this in the next couple of days.
:+1: on making intervals configurable.
However, one could argue that a more 'real world' scenario would not involve the (very nice) interval slider, but rather by the wish: I want thumbs for every 5th second only, and also want to _create_ a thumbnail for only every 5th second and not for every second. While your solution is obviously very flexible, it would mean lots of unused resources (or scripting the removal of them) when batch creating thumbs.
Do you see what I'm getting at?
Can maybe implemented with another option.
Need also to test because I can't get the slider to have any effect for the demo, as changing the value does not reload the player with an updated config (unless I'm overlooking something).

**Comment by Dalesjo** [comment]
@blacktrash 

No the slider is not part of my commit its only for demonstration, my bad that i didn't make that clear.

My modification works just like you are describing, so I'm totally seeing what you getting to :) . You configure the plugin like this for an five second interval between thumbnails:

```
thumbnails: {
    interval: 5,
    template: '/directory/{time}.jpg'
}
```

To create your thumbnails you can do like below. you set fps=1/5 for one picture every five seconds, when you run jpegtran you rename the files using *5 so the pictures name is its number of seconds from start.

`ffmpeg -i source.mp4 -vf scale=-1:180,fps=1/5 -qscale:v 5 %1d-X.jpg`
`for j in *.jpg; do jpegtran -copy none -optimize -outfile $((${j%-X.jpg}*5)).jpg ${j%}; done`
`rm *-X.jpg`

files created should now be 5.jpg 10.jpg 15.jpg 20.jpg .........

You can see the result in this example, I have preload=true in this example so it might be a bit slow to start but it works with preload=false also. (see commit for modification of preload)
http://samuel.dalesjo.com/other/flowplayer-thumbnail-fork/minimal.htm

The slider on the first example was just to demonstrate that you can use whatever interval you prefer, it updated Flowplayer without a reload. if you open a network console for you browser you should see that then the slider is on interval=4 it gets images with an multiple of 4, like 4.jpg 8.jpg 12.jpg and so worth. if you move the slider to an different value you get an multiple of that value.

**Comment by phloxic** [comment]
@Dalesjo - sure, sure. But have pity on users less familiar with shell scripting, or on me who would like to avoid to write a shell scripting guide here ;-)
What I had in mind was an option where you could keep the sequential numbering done by ffmpeg (or another tool), so that the interval between 1.jpg and 2.jpg is 5 secs. Otherwise this will turn into a support nightmare. Yes, you could argue that it is already, once you write ffmpeg somewhere, hehe, but still ...

**Comment by Dalesjo** [comment]
@blacktrash hehe well i wont argue, I made a new commit, this version is uses sequential numbering.

testpage: http://samuel.dalesjo.com/other/flowplayer-thumbnail-fork2/minimal.htm

**Comment by phloxic** [comment]
@Dalesjo - thanks. Give me a bit of time, I'm on sick leave, and therefore was only able to nitpick ;-) and, more importantly, to mull over possible further alternatives; like: the longer the interval, the more one might have the wish to configure a completely customized array of time-image mappings ... Anyway, will merge in the next couple of days, and thanks very much!.

**Pull request merged**
